apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-cronjob
  namespace: staging
spec:
  schedule: 0 5 * * 0-4
  concurrencyPolicy: Allow
  suspend: true
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: scale-up-container
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - '-c'
              args:
                - |
                  kubectl -n staging scale deployment --replicas=1 --all
              resources:
                limits:
                  cpu: 100m
                  memory: 150Mi
                requests:
                  cpu: 100m
                  memory: 150Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: crondeploy
          serviceAccount: crondeploy
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
