apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crondeploy
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: crondeploy
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crondeploy
