apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-volume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs-volume-id}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-efs-pvc  # sonar-sonarqube-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi