apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner
  namespace: lens-metrics
  uid: 5ea9fb15-01fe-40e8-bacf-552d30071509
  resourceVersion: '150338776'
  generation: 3
  creationTimestamp: '2022-01-07T13:03:52Z'
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"efs-provisioner","namespace":"lens-metrics"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"efs-provisioner"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"efs-provisioner"}},"spec":{"containers":[{"env":[{"name":"FILE_SYSTEM_ID","valueFrom":{"configMapKeyRef":{"key":"file.system.id","name":"efs-provisioner"}}},{"name":"AWS_REGION","valueFrom":{"configMapKeyRef":{"key":"aws.region","name":"efs-provisioner"}}},{"name":"PROVISIONER_NAME","valueFrom":{"configMapKeyRef":{"key":"provisioner.name","name":"efs-provisioner"}}},{"name":"AWS_ACCESS_KEY_ID","value":"AKIAWQ2RS3LBDDVBVIX7"},{"name":"AWS_SECRET_ACCESS_KEY","value":"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"}],"image":"quay.io/external_storage/efs-provisioner:latest","name":"efs-provisioner","volumeMounts":[{"mountPath":"/persistentvolumes","name":"pv-volume"}]}],"volumes":[{"name":"pv-volume","nfs":{"path":"/","server":"fs-0fd12c6b0ae6009d6.efs.eu-west-1.amazonaws.com"}}]}}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-07T13:03:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"efs-provisioner"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"AWS_ACCESS_KEY_ID"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"AWS_REGION"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:configMapKeyRef:
                          .: {}
                          f:key: {}
                          f:name: {}
                    k:{"name":"AWS_SECRET_ACCESS_KEY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"FILE_SYSTEM_ID"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:configMapKeyRef:
                          .: {}
                          f:key: {}
                          f:name: {}
                    k:{"name":"PROVISIONER_NAME"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:configMapKeyRef:
                          .: {}
                          f:key: {}
                          f:name: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/persistentvolumes"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"pv-volume"}:
                  .: {}
                  f:name: {}
                  f:nfs:
                    .: {}
                    f:path: {}
                    f:server: {}
    - manager: node-fetch
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-25T12:06:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:spec:
              f:tolerations: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-29T19:40:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
  selfLink: /apis/apps/v1/namespaces/lens-metrics/deployments/efs-provisioner
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-11-25T12:04:38Z'
      lastTransitionTime: '2022-01-07T13:03:52Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "efs-provisioner-cc5dd79c7" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-11-29T19:40:46Z'
      lastTransitionTime: '2022-11-29T19:40:46Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efs-provisioner
    spec:
      volumes:
        - name: pv-volume
          nfs:
            server: fs-0fd12c6b0ae6009d6.efs.eu-west-1.amazonaws.com
            path: /
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: AWS_ACCESS_KEY_ID
              value: gggggggggg
            - name: AWS_SECRET_ACCESS_KEY
              value: ffffff
          resources: {}
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: permanent
          operator: Equal
          value: 'true'
          effect: NoExecute
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
