apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: traccar
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traccar
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 10
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10
