apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
  namespace: logging
type: Opaque
data:
  ELASTICSEARCH_PASSWORD: ${elasticsearch-password}
  ELASTICSEARCH_HOSTS: ${elasticsearch-host-endpoint}
  ELASTICSEARCH_USERNAME: ${elasticsearch-user(kibana_system)}
