apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
  namespace: logging
type: Opaque
data:
  ELASTICSEARCH_PASSWORD: UHJvbWl6ZUAxMjNoZ3FSak4zdw==
  ELASTICSEARCH_URL: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMA==
  ELASTICSEARCH_USERNAME: a2liYW5hX3N5c3RlbQ==
