apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${name-of-role-binding}
  namespace: ${namespace-name} 
subjects:
  - kind: ServiceAccount
    name: ${name-of-sa}
    namespace: users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${name-of-role}

