apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: mon
rules:
  - verbs:
      - get
      - list
      - watch
      - exec
      - create
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - pods/exec
      - secrets
      - namespaces

