apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: mon
subjects:
  - kind: ServiceAccount
    name: admin-sa
    namespace: users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role

