kind: PersistentVolume
apiVersion: v1
metadata:
  name: efs-elasticsearch-pv-shared-log
spec:
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs-volume-id}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-shared-log
  volumeMode: Filesystem
