kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch-log
  template:
    metadata:
      labels:
        io.kompose.service: elasticsearch-log
    spec:
      volumes:
        - name: efs-elasticsearch-volume-shared-log
          persistentVolumeClaim:
            claimName: efs-elasticsearch-pvc-shared-log
      containers:
        - name: elasticsearch
          image: 'docker.elastic.co/elasticsearch/elasticsearch:8.8.0'
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: xpack.security.enabled
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms256m -Xmx490m'
            - name: TZ
              value: Asia/Kolkata
            - name: discovery.type
              value: single-node
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
            - name: efs-elasticsearch-volume-shared-log
              mountPath: /var/lib/elasticsearch/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
