apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /
    server: ${NAS-ID}.${region-id}.nas.aliyuncs.com 
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - tcp
    - noresvport
    - vers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
