apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner
  namespace: lens-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efs-provisioner
    spec:
      volumes:
        - name: pv-volume
          nfs:
            server: fs-0fd12c6b0ae600j9999d6.efs.eu-west-1.amazonaws.com #arn of EFS 
            path: /
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: AWS_ACCESS_KEY_ID
              value: gggggggggg
            - name: AWS_SECRET_ACCESS_KEY
              value: ffffff
          resources: {}
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: permanent
          operator: Equal
          value: 'true'
          effect: NoExecute
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
