apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins-ns
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-class: aws-efs
    volume.beta.kubernetes.io/storage-provisioner: example.com/aws-efs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: pvc-cae5d60992-e823-4a35-a700-b088304cafab8a
  volumeMode: Filesystem
